## Use root/example as user/password credentials
#version: '3.1'
#
#services:
#
#  db:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: nodejs
#    ports:
#    - '3306:3306'
#    # (this is just an example, not intended to be a production configuration)

version: '3.7'

services:
  mysql:
    platform: linux/x86_64
    image: mysql
    container_name: mysql-nodejs
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nodejs
    ports:
      - "3306:3306"
#    volumes:
#      # Mysql
#      - db:/var/lib/mysql
#    networks:
#      - nodejss
